# Site settings
title: Jams
email: ju2pom+blog@gmail.com
description: A C#/WPF coder journey
baseurl: ""
url: ""

author:
  name     : 'Julien Amsellem'
  email    : ju2pom+blog@gmail.com
  url      : 
  facebook : 
  twitter  : http://twitter.com/julienju2pom

github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "ju2pom"
google_analytics: 

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
