# Site settings
title: Coder journey
email: ju2pom+blog@gmail.com
description: A C#/WPF coder journey
baseurl: ""
url: ""

author:
  name     : 'Julien Amsellem'
  email    : ju2pom+blog@gmail.com
  url      : 
  facebook : 
  twitter  : http://twitter.com/julienju2pom

github: https://github.com/ju2pom
disqus_shortname: "https-ju2pom-github-io"
google_analytics: "UA-98794260-1"

paginate: 4
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
highlighter : rouge
permalink : /:title/

gems:
  - jekyll-seo-tag
  #- jemoji
